[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "first-web-scraper"
version = "1.0.0"
description = "A step-by-step guide to writing a web scraper with Python."
readme = "README.md"
requires-python = "==3.13.*"
license = "GPL-3.0-or-later"
dependencies = [
    "requests",
    "bs4",
    "sphinx",
    "sphinx-autobuild",
    "myst-parser",
    "sphinx-palewire-theme>=0.1.10",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.13",
]

[dependency-groups]
dev = [
    "pre-commit",
]

[tool.setuptools]
packages = []
